apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-config
  labels:
    app: {{ include "postgresql.name" . }}
data:
  POSTGRESQL_DB_USERNAME: {{ .Values.env.POSTGRESQL_DB_USERNAME }}
  POSTGRESQL_DB_PASSWORD: {{ .Values.env.POSTGRESQL_DB_PASSWORD }}
  POSTGRESQL_DB_HOST: {{ .Values.env.POSTGRESQL_DB_HOST }}
  POSTGRESQL_DB_PORT: {{ .Values.env.POSTGRESQL_DB_PORT | quote }}
  POSTGRESQL_DB_NAME: {{ .Values.env.POSTGRESQL_DB_NAME }}
  POSTGRESQL_DB_SCHEMA: {{ .Values.env.POSTGRESQL_DB_SCHEMA }}
  HTTP_PORT: {{ .Values.env.HTTP_PORT | quote }}
  SWAGGER_UI_ENABLED: {{ .Values.env.SWAGGER_UI_ENABLED | quote }}
